# ----------------------------------------------------------------------------------------------------------------------
# Jenkins base service
# ----------------------------------------------------------------------------------------------------------------------

# docker-compose.yaml
version: '3.8'
services:
    jenkins:
        container_name: artemis-jenkins
        image: duongaity/artemis-jenkins
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        ports:
            - 8082:8080
        expose:
            - "8080"
        volumes:
            - artemis-jenkins-data:/var/jenkins_home # store data jenkins( config, job, plugin)
            - /var/run/docker.sock:/var/run/docker.sock # allow jenkins control docker on host
            - /var/run/docker:/var/run/docker # access docker run 
        environment:
            - JAVA_OPTS="-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true" # disable crsf
        user: root
        networks:
            - artemis
  # proxy:
  #   restart: unless-stopped
  #   image: nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - jenkins
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
    artemis:
        driver: "bridge"
        name: artemis
volumes:
    artemis-jenkins-data:
        name: artemis-jenkins-data
